# Generated by Django 4.2.10 on 2024-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_class_master_alter_user_master_regis_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='train_mastership',
            new_name='train_master',
        ),
        migrations.AlterModelTable(
            name='station_master',
            table='stationMaster',
        ),
        migrations.AlterModelTable(
            name='train_master',
            table='train_master',
        ),
        migrations.AlterModelTable(
            name='user_feedback',
            table='user_feedback',
        ),
        migrations.AlterModelTable(
            name='user_master',
            table='user_master',
        ),
    ]
