# Generated by Django 4.2.10 on 2024-03-04 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_master_regis_date_schedulemaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_master',
            name='available_seats',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='source_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_station', to='home.station_master', verbose_name='Source Station'),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterModelTable(
            name='station_master',
            table='station_master',
        ),
    ]
