# Generated by Django 4.2.10 on 2024-03-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_train_master_available_seats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_schedule',
            old_name='start_time',
            new_name='depart_time',
        ),
        migrations.AlterField(
            model_name='station_master',
            name='station_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='station_master',
            name='station_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
