# Generated by Django 5.0.3 on 2024-03-06 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_start_time_train_schedule_depart_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 3, 6)),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
