# Generated by Django 4.2.10 on 2024-03-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_user_master_regis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 3, 7)),
        ),
    ]
