# Generated by Django 4.2.11 on 2024-03-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_train_master_depart_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_master',
            old_name='depart_datetime',
            new_name='depart_time',
        ),
    ]
