# Generated by Django 4.2.10 on 2024-03-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_depart_datetime_train_master_depart_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestation',
            options={},
        ),
        migrations.RemoveField(
            model_name='routemaster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routemaster',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='train_master',
            name='arrival_datetime',
        ),
        migrations.AddField(
            model_name='train_master',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(14, 49, 54, 141073)),
        ),
        migrations.AddField(
            model_name='train_master',
            name='depart_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='available_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(14, 49, 54, 141073)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
