# Generated by Django 4.2.11 on 2024-03-08 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_routestation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(18, 49, 30, 412553)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(18, 49, 30, 412553)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='journey_duration',
            field=models.CharField(max_length=20),
        ),
    ]
