# Generated by Django 4.2.10 on 2024-03-09 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_train_master_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='routestation',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(9, 26, 39, 914762)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(9, 26, 39, 914762)),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 3, 9)),
        ),
    ]
