# Generated by Django 4.2.10 on 2024-03-09 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_routestation_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(13, 38, 11, 221582)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(13, 38, 11, 221582)),
        ),
    ]
