# Generated by Django 4.2.10 on 2024-03-10 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_station_master_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(16, 21, 14, 652427)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(16, 21, 14, 652427)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='dest_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_station', to='home.station_master'),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='source_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_station', to='home.station_master', verbose_name='Source Station'),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 3, 10)),
        ),
    ]
