# Generated by Django 4.2.10 on 2024-03-10 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_train_master_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(16, 42, 9, 597900)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(16, 42, 9, 597900)),
        ),
    ]
