# Generated by Django 4.2.10 on 2024-03-28 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_train_master_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket_master',
            fields=[
                ('PNR_NO', models.IntegerField(primary_key=True, serialize=False)),
                ('coach_typ', models.CharField(max_length=20)),
                ('seat_number', models.IntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_state', models.CharField(choices=[('R', 'Reserved'), ('A', 'Allocated'), ('P', 'Paid'), ('N', 'Not Paid')], max_length=1)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_ticket', to='home.station_master')),
            ],
        ),
        migrations.RenameField(
            model_name='class_master',
            old_name='price',
            new_name='fare',
        ),
        migrations.RemoveField(
            model_name='train_master',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='train_master',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='train_master',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='train_master',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(1, 56, 51, 625785)),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(default=datetime.time(1, 56, 51, 625785)),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 3, 29)),
        ),
        migrations.AlterModelTable(
            name='routestation',
            table='routestation',
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
        migrations.AddField(
            model_name='ticket_master',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_classes', to='home.class_master'),
        ),
        migrations.AddField(
            model_name='ticket_master',
            name='depart_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_ticket', to='home.station_master'),
        ),
        migrations.AddField(
            model_name='ticket_master',
            name='pass_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.passenger_master'),
        ),
        migrations.AddField(
            model_name='ticket_master',
            name='train_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='home.train_master'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket_master',
            unique_together={('PNR_NO', 'train_no')},
        ),
    ]
