# Generated by Django 4.2.10 on 2024-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_station_master_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_master',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='arrival_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='train_master',
            name='depart_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
