# Generated by Django 4.2.10 on 2024-03-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_train_master_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemaster',
            name='destination_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='home.station_master', to_field='station_code'),
        ),
        migrations.AlterField(
            model_name='routemaster',
            name='source_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_routes', to='home.station_master', to_field='station_code'),
        ),
    ]
