# Generated by Django 4.2.10 on 2024-03-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_routemaster_destination_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemaster',
            name='travel_time',
        ),
    ]
