# Generated by Django 4.2.10 on 2024-04-06 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_routemaster_travel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_master',
            name='pass_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 4, 6)),
        ),
    ]
