# Generated by Django 4.2.10 on 2024-04-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_ticket_master_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_master',
            options={'ordering': ['PNR_NO']},
        ),
       
    ]
