# Generated by Django 4.2.10 on 2024-04-16 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_ticket_master_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_master',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='ticket_master',
            name='coach_typ',
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
