# Generated by Django 4.2.10 on 2024-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_class_master_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_master',
            name='coach_no',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
