# Generated by Django 4.2.10 on 2024-04-17 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_ticket_master_coach_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_no', models.CharField(max_length=10)),
                ('capacity_passen', models.PositiveIntegerField()),
                ('coach_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.class_master')),
            ],
            options={
                'db_table': 'coach_master',
            },
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 4, 18)),
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coach')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
    ]
