# Generated by Django 4.2.10 on 2024-04-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_coach_alter_user_master_regis_date_seat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coach',
            table='coach',
        ),
    ]
