# Generated by Django 4.2.10 on 2024-04-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_coach_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coach', to_field='coach_no'),
        ),
    ]
