# Generated by Django 4.2.10 on 2024-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_coach_coach_no_alter_seat_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger_master',
            name='seat_no',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket_master',
            name='seat_number',
            field=models.CharField(max_length=255),
        ),
    ]
