# Generated by Django 4.2.10 on 2024-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_passenger_master_seat_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_master',
            name='arrival_datetime',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket_master',
            name='departure_datetime',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
