# Generated by Django 4.2.10 on 2024-04-23 08:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_ticket_master_coach_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_master',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to='home.user_master', to_field='username'),
        ),
        migrations.AlterField(
            model_name='ticket_master',
            name='booking_state',
            field=models.CharField(choices=[('R', 'Reserved')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='regis_date',
            field=models.DateField(default=datetime.date(2024, 4, 23)),
        ),
        migrations.AlterModelTable(
            name='payment_master',
            table='payment_master',
        ),
        migrations.AlterModelTable(
            name='schedulemaster',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='ticket_master',
            table='ticket_master',
        ),
        migrations.DeleteModel(
            name='routestation',
        ),
    ]
